"""table: create PersonModel

Revision ID: 160a9fd3f494
Revises: 
Create Date: 2021-04-13 21:43:39.838158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160a9fd3f494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_firstname', sa.String(length=10), nullable=False),
    sa.Column('person_lastname', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
