"""removed unused models: PersonModel

Revision ID: 1ba62d57b65e
Revises: fee7baea4e84
Create Date: 2021-04-14 22:55:02.541447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba62d57b65e'
down_revision = 'fee7baea4e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_firstname', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('person_lastname', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persons_pkey')
    )
    # ### end Alembic commands ###
